version: "3.9"
services:
  scrum-board:
    container_name: scrum_board_backend
    build:
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - db
    env_file: .env

  db:
    restart: always
    image: postgres:13.3
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "scrum-board-db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - "5439:5432"
